package fan;

/**
 * Interface to be used by all random number generators in this
 * simulator
 */
public interface Randomize {
	
	/**
	 * Get number generated by this generator
	 * @param range The range of the numbers generated by this generator
	 * @return Generated number
	 */
	public double getNumber(double range);
}
